### ISSUE TITLE
커밋 전에 Lint 되도록 설정하기 (Google Java Style Guide)

### ISSUE THREAD

**Issue by Dong-Hyeon-Yu** [InhaBas/Inhabas.com-api#118]
표준 가이드 링크 : https://google.github.io/styleguide/javaguide.html

git hook 으로 푸시 넣기 전에 설정되도록 해보기

- git push 시 코드 컨벤션 검사 (불필요한 여백이나 잘못된 컨벤션) 과정 github action에 추가하는 과정 고려

**Comment by skytin1004** [comment]
Google Java Style Guide 에서는 Static Import를 제한하고 있어서 자체 IBAS 포멧팅을 사용하고 이 양식에 맞게 검사하는 방향 고안중
