### ISSUE TITLE
Mock 테스트 하는 법. (aka. 서비스와 컨트롤러를 unit 테스트 해보자)

### ISSUE THREAD

**Issue by Dong-Hyeon-Yu** [InhaBas/Inhabas.com-api#33]

**Comment by MingyeomKim** [comment]
BoardServiceTest에서 write를 테스트하는 상황
--> write에서 사용하는 BoardRepository를 Mocking, 
when().thenReturn() 메소드로 write시 내부적으로 호출되는 모든 함수들을 mocking한다. 

ex) when(boardRepository.save(any()).thenReturn(saveBoardDto);

이후 verify로 원하는 함수가 잘 호출되었는지 확인한다.
